### ISSUE TITLE
discoverCharacteristics undefined

### ISSUE THREAD

**Issue by monofuel** [monofuel/blebot9000#1]
```
monofuel@Ifrit:~/src/blebot$ node init.js 
make sure you arent already paired and connected!
connecting to FIRMATA
/home/monofuel/src/blebot/node_modules/ble-serialport/node_modules/blue-yeast/lib/node/blue_yeast.js:102
          services[0].discoverCharacteristics([BLE_RX_UUID, BLE_TX_UUID],
                     ^

TypeError: Cannot read property 'discoverCharacteristics' of undefined
    at /home/monofuel/src/blebot/node_modules/ble-serialport/node_modules/blue-yeast/lib/node/blue_yeast.js:102:22
    at Peripheral.<anonymous> (/home/monofuel/src/blebot/node_modules/ble-serialport/node_modules/blue-yeast/node_modules/noble/lib/peripheral.js:73:7)
    at Peripheral.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Peripheral.emit (events.js:169:7)
    at Noble.onServicesDiscover (/home/monofuel/src/blebot/node_modules/ble-serialport/node_modules/blue-yeast/node_modules/noble/lib/noble.js:208:16)
    at emitTwo (events.js:87:13)
    at null.emit (events.js:172:7)
    at null.NobleBindings.onServicesDiscovered (/home/monofuel/src/blebot/node_modules/ble-serialport/node_modules/blue-yeast/node_modules/noble/lib/hci-socket/bindings.js:291:8)
    at emitTwo (events.js:87:13)
```

**Comment by monofuel** [comment]
fixed by using pvanallen/ble-serial
